name: Keep Streamlit App Alive

on:
  schedule:
    # Executa a cada 6 horas (você pode ajustar conforme necessário)
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Permite execução manual através da interface do GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.STREAMLIT_APP_URL }})
          echo "Status code: $response"
          if [ "$response" = "200" ]; then
            echo "Ping successful!"
          else
            echo "Ping returned status code: $response"
          fi
      - name: Log timestamp
        run: echo "Ping sent at $(date)"
